import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import About from "../components/About";
import Bottom from "../components/Bottom";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Navigation from "../components/Navigation";
import SectionOne from "../components/SectionOne";

const Home: NextPage = () => {
  const [isNav, setIsNav] = useState(false);

  console.log(isNav);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" min-h-screen bg-black relative">
        <div
          className={` ${
            isNav ? "opacity-100 z-50 " : " opacity-0 -z-10"
          } absolute duration-500 ease-in-out bg-back h-full w-full `}
        >
          <Navigation isNav={isNav} setIsNav={setIsNav} />
        </div>
        <div className=" z-50">
          <div
            className={` ${
              isNav ? "opacity-0" : " opacity-100 z-50"
            } mx-[23px] md:mx-[81px] duration-500 ease-in-out z-50`}
          >
            <div>
              <Navbar isNav={isNav} setIsNav={setIsNav} />
            </div>

            <div className=" mt-[50px]">
              <Header />
            </div>

            <div className=" my-[145px]">
              <About />
            </div>

            <div>
              <SectionOne />
            </div>

            <div className=" pt-[100px] pb-[50px]">
              <Bottom />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
